### ISSUE TITLE
Remove __init__.pyc

### ISSUE THREAD

**Issue by gabru-md** [yogdaan/varnan#15]
Delete `__init__.pyc` from `https://github.com/yogdaan/varnan/tree/master/controllers`
It is not considered a good practice to commit `.pyc` files along with the source code.

Can be taken up by any beginner :)

**Comment by Manas-kashyap** [comment]
I am taking it up

**Comment by gabru-md** [comment]
@Manas-kashyap you need to delete the `__init__.pyc` file.

Please send a PR for the same. :D

**Comment by gabru-md** [comment]
Please join the organisation so that I can assign the issue to you :)

**Comment by Manas-kashyap** [comment]
@gabru-md joined , and , just i need to delete it , thats it right ?

**Comment by xeon-zolt** [comment]
#16
